### ISSUE TITLE
Fix .gitignore file

### ISSUE THREAD

**Issue by bleskows** [PTC-ALM/TortoiseSI#113]
Debug configuration build adds the following paths that are currently not ignored:
/ext/scintilla/win32/Debug
/ext/scintilla/win32/x64/Debug
/src/Debug
/src/x64/Debug

A little annoying to have to revert these files before I commit after I build, so might as well add them to .gitignore.

**Comment by KristinaTaylor** [comment]
Build issue. Closing.
