### ISSUE TITLE
Submit CP Dialog should use TortoiseSI logo

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#126]
Currently, the submit CP dialog shows the PTC logo. We should be consistently using the TortoiseSI logo for TortoiseSI views & dialogs, even though some actions launch PTC Integrity Client UIs.

**Comment by KristinaTaylor** [comment]
I currently can't get this gesture to work in build 168. There is no particular information available in my event viewer log. Is there some other information I could provide to help debug the problem?

**Comment by krrish1008** [comment]
Can you please upload a screen shot of what you get when you hit Submit CP.
It seems to work on my machine. not sure what is happening

**Comment by KristinaTaylor** [comment]
My reported problem appears to be fixed in build 169. Thank you!

I also see the new icon, so I will close this issue once the pull request is merged. The icon change doesn't need a test case/regression test.

**Comment by KristinaTaylor** [comment]
Pull request is merged and fix is available in build 170. Closing the issue.
