### ISSUE TITLE
Need a usable way to remove filters from the ignore list

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#135]
Under issue #31 we added the ability to add things to the client's non-members file filter. We should expose a simple way to allow the user to remove things from this filter.

**Comment by sharonzhao** [comment]
Verified with build #197 that remove filters from the ignore list works (test case 1067387 in TortoiseSI test suite 1012724).

This issue can be closed.

**Comment by KristinaTaylor** [comment]
Closed based on testing notes above.
