### ISSUE TITLE
Provide a shortcut to "View my Change Packages"

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#136]

**Comment by KristinaTaylor** [comment]
The new menu item currently reads "View my Change Package." Can this be updated to "View my Change Packages"?

**Comment by sharonzhao** [comment]
Verified with build #197. Executed test case 1065691 in TortoiseSI test suite (1012724) and verified the "View My Change Packages" shortcut worked correctly - it displayed all the active change packages of the current user.

This issue can be closed.

**Comment by KristinaTaylor** [comment]
Closing based on testing notes above.
