### ISSUE TITLE
Provide a shortcut to "View My Reviews"

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#137]
Should show: si viewcps --myReviews -g

**Comment by sharonzhao** [comment]
"View My Reviews" is not working currently.

After talking with Krishaan, I confirmed that he knows how this was broken. He'll fix it soon and create a pull request. This issue will be verified once the fix is in the build.

**Comment by sharonzhao** [comment]
When the menu item "View My Reviews" is selected, all of the user's Change package reviews are shown. (1065700 in TortoiseSI test suite).

Tested the issue with build 205.

**Comment by sharonzhao** [comment]
This issue can be closed.

**Comment by atusek** [comment]
Closing as per test notes.
