### ISSUE TITLE
Provide a shortcut to resolve merge conflicts

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#138]
Users need a way to resolve merge conflicts. This should be exposed through the "si merge" command.

**Comment by KristinaTaylor** [comment]
I think merge conflict resolution should only be available on files, rather than on folders. If possible, can we also make it only available if the file has the status of "marked for later merge"?

**Comment by KristinaTaylor** [comment]
I just did a quick sanity check of this, and I was prompted for a sandbox when I tried to run the merge resolution, and Integrity tried to merge every member in the sandbox I chose, not just the one I had selected. Are we missing specifying the selection? When I run "si merge -g <file name>" I seem to get the results I would expect from this menu shortcut.

**Comment by KristinaTaylor** [comment]
Sanity check on build 174 looks good. Thanks!

**Comment by sharonzhao** [comment]
Merge Conflicts is working properly. Executed test case 1065722 in TortoiseSI test suite. Verified on build 205.

This issue can be closed.

**Comment by KristinaTaylor** [comment]
Closing per testing notes above.
