### ISSUE TITLE
Automatically generate build numbers for the artifacts

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#14]
Gilad thinks there's a header and an installer file which need to be modified in order to make this happen.

**Comment by bleskows** [comment]
The AppVeyor Rest API (http://www.appveyor.com/docs/api) could be used to get project last build.

Gilad's suggestion: call the API via a Powershell script before build and generate the files with the appropriate version

**Comment by bleskows** [comment]
Actually, even easier way of doing it. We have access to the build number through the AppVeyor build process environment variables. We can have a PS script that will modify the appropriate files after cloning and just before the build process.

**Comment by sharonzhao** [comment]
Verified with build 1.0.43.0 that the version number for the installer matches the AppVeyor build number.
