### ISSUE TITLE
User incorrectly told that a sandbox can't be created

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#143]
Code which is checking whether or not any top level sandbox is an ancestor of the directory where the sandbox is being created is passing the parameters in the wrong order.
This is resulting in an erroneous result that prevents user from creating sandboxes.

**Comment by sharonzhao** [comment]
Sandbox can be created properly in the applicable locations. No error occurred. Executed all create sandbox test cases under the heading "Basic Sandbox Operations" (1019608 in TortoiseSI test suite).

Tested the issue with build 197.

**Comment by sharonzhao** [comment]
This issue can be closed.

**Comment by KristinaTaylor** [comment]
Closing per testing notes above.
