### ISSUE TITLE
Viewing TortoiseSI properties on folder throws an exception

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#149]
If you go to the TortoiseSI tab of the windows properties page, on a folder, you get the following error on Windows 2008 Server. 

![crash](https://cloud.githubusercontent.com/assets/10520385/9068876/f491fe0a-3ab3-11e5-8648-22543e3baa4d.PNG)

On Windows 7, Explorer hangs.

**Comment by atusek** [comment]
@KristinaTaylor The properties page contains file properties. Shall the properties page be unavailable when a folder is selected?

![image](https://cloud.githubusercontent.com/assets/6186615/9086948/c7302728-3b55-11e5-83bc-e73ff395efb8.png)

**Comment by KristinaTaylor** [comment]
I think it would be really useful to have it show at least the subproject's latest checkpoint and variant information, if applicable. If you use the Eclipse integration, take a look at what's available when you select a subproject in Eclipse, and go to properties (the Integrity tab, specifically).

**Comment by atusek** [comment]
@KristinaTaylor This is how the folder properties page is shaping up. Any feedback?

 ![image](https://cloud.githubusercontent.com/assets/6186615/9136124/0c8b64bc-3ce2-11e5-8f31-8cd559edd6ec.png)

**Comment by KristinaTaylor** [comment]
@atusek Looks great!

**Comment by sharonzhao** [comment]
Added test case 1087472 in TortoiseSI test suite to test this issue. Verified with build 197 that viewing TortoiseSI properties on folder did not throw exception, and folder properties were displayed correctly.

This issue can be closed.

**Comment by KristinaTaylor** [comment]
Closing as per testing notes above.
