### ISSUE TITLE
Where do results of builds go?

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#15]
Are they available to anyone outside of the AppVeyor account being used?

The expectation is that at least the TortoiseSI team would be able to get access. There is no requirement that the builds be hidden from public access.

**Comment by bleskows** [comment]
We'll need to configure appveyor.yml to specify how artifacts are packaged (i.e. tell AppVeyor which files and folder should be uploaded to AppVeyor cloud storage during the build, http://www.appveyor.com/docs/packaging-artifacts for reference).

Ideally, we would also like these artifacts deployed to a remote FTP location (http://www.appveyor.com/docs/deployment/ftp for reference)

**Comment by bleskows** [comment]
Code changes in pull request #25 for issue #14

**Comment by KristinaTaylor** [comment]
The latest build can be found here: http://ci.appveyor.com/project/PTC-ALM/tortoisesi

I just chatted with Gilad and Blaise, and going forward, we should ensure that we only "verify" issues that have already been merged into "master".

@bleskowskyPTC can you identify how someone can tell, from the [build history](http://ci.appveyor.com/project/PTC-ALM/tortoisesi/history), which ones are builds of master, and which are builds of a branch?

**Comment by bleskows** [comment]
![pullrequestvsmergedchanges](https://cloud.githubusercontent.com/assets/10633761/6004339/15ac224c-aad0-11e4-8bf4-7d79106ac600.png)

Refer to above screenshot. If you look at the build history, builds like the ones I have highlighted in red have a pull request associated with them. These are not yet merged into the remote master (i.e. PTC-ALM/TortoiseSI master).

Notice that the one marked in green has no Pull Request and has "Merge pull request #25" in the description. This is how you would identify that this is a build from the remote master (i.e. we should verify this).

In general, the easiest way to determine a master build is that **it has no pull request associated with it**. "Merge **pull request**" in the build description is also another indicator.

**Comment by bleskows** [comment]
We have modified the AppVeyor configuration to be built on PTC-ALM credentials. Code changes for this are in Pull Request #27

**Comment by sharonzhao** [comment]
Verified with the latest build 1.0.9.0:
Here the build goes: https://ci.appveyor.com/project/PTC-ALM/tortoisesi
