### ISSUE TITLE
Add a shortcut for "View related Change Packages"

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#153]
A customer has requested that TortoiseSI expose a gesture that launches a view that shows all change packages related to the project represented by the selected sandbox/subsandbox.

This can be done using a filter on the si viewcps command. The filters need to account for both the relevant project and the associated configuration - mainline or a variant.

**Comment by cwarnerPTC** [comment]
The si viewcps command does not appear to be a published command.

**Comment by KristinaTaylor** [comment]
As I mentioned in #162 I think using a non-published command in this case is fine.

**Comment by sharonzhao** [comment]
Added test case 1088802 in TortoiseSI test suite to test this issue. Verified on build 216 that "View Related Change Packages" worked properly.

This issue can be closed.

**Comment by KristinaTaylor** [comment]
Closing as per testing notes above.
