### ISSUE TITLE
Resync should be available on a folder

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#157]
Users would like the ability to select a sub-folder inside a sandbox, and resync recursively from that point down.

There should be a command available in the Working File API that takes a folder selection and converts to the appropriate combination of files and folders for the si resync command. As usual, please make sure that any command used directly in the TortoiseSI code is an API published command with ITF tests written - or that an RFC is posted to publish the command in the next release.

**Comment by sharonzhao** [comment]
Added test case 1088907 in TortoiseSI test suite to test this issue. Verified on build 216 that Resynchronize was available on a folder and was working properly.

This issue can be closed.

**Comment by atusek** [comment]
Closing as per test notes above.
