### ISSUE TITLE
Drop Subproject should be available for a folder corresponding to a subproject

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#158]
When a folder inside a sandbox is selected, the drop subproject menu should be enabled. This operation should fail if a folder was selected that does not correspond directly to a subproject.

As usual, please make sure that any command used directly in the TortoiseSI code (eg: si drop) is an API published command with ITF tests written.

**Comment by sharonzhao** [comment]
Added test cases 1088950 and 1088952 in TortoiseSI test suite to test this issue. Verified on build 222 that Drop Sub-Project is available for a folder corresponding to a subproject, and the subproject is dropped successfully.

However, whenever I clicked on a folder which does not correspond to a subproject, I got the following error:
![sandboxinfo error right clicking on folders in windows explorer](https://cloud.githubusercontent.com/assets/10675313/10233268/7a29642a-685b-11e5-830f-493d3c690556.jpg)
![projectinfo error right clicking on folders in windows explorer](https://cloud.githubusercontent.com/assets/10675313/10233188/0deb610a-685b-11e5-8879-7b3dbf5116e3.jpg)

**Comment by sharonzhao** [comment]
The above error didn't occur anymore when a folder which does not correspond to a subproject was clicked. Verified on build 225.

This issue can be closed.

**Comment by KristinaTaylor** [comment]
Closing based on testing notes.
