### ISSUE TITLE
Add a shortcut for "View my Locks"

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#159]
Enablement should be the same as "View my Change Packages" or "View my Reviews" and this should be in that menu group as well.

This menu operation should have an icon related to locks - talk to me when you have some ideas for us to choose from. We should take this opportunity to reconsider the icons chosen for "View my Change Packages" and "View my Reviews" too - is there anything more appropriate available, rather than using the same one as "View Sandbox"?

**Comment by cwarnerPTC** [comment]
I believe the Integrity command for this is si locks --locker=[your own username]. The si locks command is a published command.

**Comment by atusek** [comment]
There is an API call to retrieve the user name from a the response object:

mksrtn  mksResponseGetConnectionUsername (const mksResponse res, wchar_t *buf, size_t len)
    Function used to retrieve the username for the application connection.

This can be used to retrieve the locks belonging to the specific user as mentioned above - si locks -g --locker=[username]. An initial command will have to be run to retrieve the username (si sandboxinfo can be used).

Thanks to Kristina for her help with this!

**Comment by sharonzhao** [comment]
Added test case 1088863 in TortoiseSI test suite to test this issue. Verified on build 216 that "View My Locks" worked properly.

This issue can be closed.

**Comment by KristinaTaylor** [comment]
Closing per testing notes.
