### ISSUE TITLE
Provide a shortcut for "View Project History"

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#161]
The command to run this view should use the sandbox to provide the context, so that the view has the appropriate checkpoint highlighted, and the appropriate context for any commands launched from this view.

**Comment by cwarnerPTC** [comment]
Integrity Command = si viewprojecthistory. Does not appear to be a published command.

**Comment by KristinaTaylor** [comment]
As I mentioned in #162 I think using a non-published command in this case is fine.

**Comment by sharonzhao** [comment]
Added test case 1088896 in TortoiseSI test suite to test this issue. Verified on build 216 that "View Project History" worked properly.

This issue can be closed.

**Comment by atusek** [comment]
Closing as per test notes above.
