### ISSUE TITLE
Provide a shortcut for "View Project Differences"

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#162]
This shortcut should run the si mods command with the sandbox providing the context. The resulting view will show the changes since the last checkpoint. 

Note: If a user would like to see changes between two specific checkpoints, they should first launch the project history, select the two checkpoints, then run the project differences command.

**Comment by cwarnerPTC** [comment]
I believe that the Integrity command for this is si mods, and it doesn't appear to be a published command.

**Comment by KristinaTaylor** [comment]
I think this being a non-API published command is fine in this case, actually. Since we're going to be just running the command with a -g, and not processing output from the command via the API, it can still be used in this integration. It is documented for use from the CLI, which is essentially what we're doing.

**Comment by sharonzhao** [comment]
Added test case 1088898 in TortoiseSI test suite to test this issue. Verified on build 216 that "View Project Differences" worked properly.

This issue can be closed.

**Comment by atusek** [comment]
Closing as per test notes above.
