### ISSUE TITLE
Error appears after client process dies and folder is refreshed

### ISSUE THREAD

**Issue by atusek** [PTC-ALM/TortoiseSI#163]
Error appears when user opens sandbox folder in Windows Explorer containing multiple files and kills client. Refreshing the folder (F5) causes this error to appear along with an Integrity login dialog:

![image](https://cloud.githubusercontent.com/assets/6186615/9684039/ee32b7e2-52e2-11e5-946b-2dc5335269d1.png)

**Comment by sharonzhao** [comment]
Added test case 1087716 in TortoiseSI test suite to test this issue. Verified on build 205 that error didn't appear after client process died and folder was refreshed.
This issue can be closed.

**Comment by atusek** [comment]
Closing as per test notes above.
