### ISSUE TITLE
Connection error dialog doesn't include any text

### ISSUE THREAD

**Issue by atusek** [PTC-ALM/TortoiseSI#164]
When a client connection cannot be made, an error dialog appears that does not contain any text.

![image](https://cloud.githubusercontent.com/assets/6186615/9821338/a95323f0-5887-11e5-8482-e0c76dc3db2e.png)

**Comment by atusek** [comment]
![tortoisesicommunicationerror](https://cloud.githubusercontent.com/assets/6186615/9944387/042ee0c6-5d55-11e5-938a-440f5e281525.jpg)

**Comment by KristinaTaylor** [comment]
That looks great!

**Comment by sharonzhao** [comment]
Added test case 1087804 in TortoiseSI test suite to test this issue. Verified on build 205 that connection error dialog appears when a client connection cannot be made, and the dialog contains the correct text.

This issue can be closed.

**Comment by KristinaTaylor** [comment]
Closing per testing notes above.
