### ISSUE TITLE
Handle mechanics around Windows File Properties pages

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#17]
We need to populate a properties page for singly selected files, with data from Integrity.

This should include:
Member Revision
Working Revision
Working CP ID
Lockers (Ideally: name, cp ID, exclusive vs non-exclusive)
Status (added, modified, renamed, moved, etc)
Sandbox/Subsandbox

Some of this information will already be available directly from the working file info command. Some may need to be obtained using the memberinfo or other Integrity commands.

**Comment by bleskows** [comment]
Removed needs docs: documented in Alpha release User Guide

**Comment by sharonzhao** [comment]
Used the following test cases in test suite 1012724 to test the windows file properties pages with build 1.0.136.0:
1035664, 1035666, 1035668, 1035670, and 1035772

**Comment by sharonzhao** [comment]
This issue cannot be closed until the renamed status bug is fixed and tested.

**Comment by atusek** [comment]
@sharonzhao Latest pull request contains fix for this issue. Once it is merged it can be tested.

**Comment by sharonzhao** [comment]
The following file properties are correctly shown on the TortoiseSI tab of the properties window of a defer renamed member file:
Member Revision   1.1
Working Revision   1.1
Working CP Id        1:1
Sandbox Name       c:/test/project.pj
Status                     Member | Renamed

Tested using build 1.0.138.0.

**Comment by sharonzhao** [comment]
This issue can be closed now.

**Comment by KristinaTaylor** [comment]
Reviewed. Closing.
