### ISSUE TITLE
Files in a controlled directory have appropriate member operations available

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#18]
**Non-members have:** Add
**Members have:** Check Out, Drop, Lock, Resynchronize by Change Package
**Modified members have:** Check In, Revert

These should all use the wf execute command. Note that Resynchronize by Change Package on files should be updated to use wf execute once it's been fixed in Integrity 10.7.

**Comment by bleskows** [comment]
Note for when we verify. Use a client build of 7876 or later. This build contains a fix for a defect where wf execute threw an out of bounds error for single character options (i.e. -g).

**Comment by bleskows** [comment]
@KristinaTaylor are these all single selection?

**Comment by KristinaTaylor** [comment]
I think they should all be multi-select, but files only. The views were single select, but I can see why someone would want to be able to select a bunch and say "add."

**Comment by bleskows** [comment]
@KristinaTaylor Here are my observations for multi-select behaviour for these operations investigating "what if there are invalid elements in a selection"?

Basically, I tested with running each command (through TortoiseSI) when there were one valid element and multiple invalid elements in the selection. Right now, these commands are enabled if there is at least one valid element in the selection.

| Command | Enable Condition | Test Scenario | Result of Execution |
| --- | --- | --- | --- |
| Add | At least one is File && Add | 1 add, 2 members | Adds non-member. Pops open "Files Not Added" dialog |
| Checkout | At least one is File && Member | 1 member, 2 adds | Checks out member. 2 warnings bundled into one dialog |
| Checkin | At least one is File && Member | 1 member, 2 adds | Doesn't check in. Pops open 1 error dialog for only 1 invalid selection element |
| Drop | At least one is File && Member | 1 member, 2 adds | Drops member. 2 warnings bundled into one dialog |
| Lock | At least one is File && Member | 1 member, 2 adds | Locks member. 2 warnings bundled into one dialog |
| Revert | At least one is File && Member | 1 member, 2 adds | Reverts member. 2 warnings bundled into one dialog |

![image](https://cloud.githubusercontent.com/assets/10633761/6562018/c626f28a-c66b-11e4-8143-8e8e6644f77c.png)
Files Not Added dialog

![image](https://cloud.githubusercontent.com/assets/10633761/6561843/b7786a76-c66a-11e4-8679-bcb7ebcbe72c.png)
2 warnings for 2 invalid elements dialog example

![image](https://cloud.githubusercontent.com/assets/10633761/6562000/92e7d3d0-c66b-11e4-9f7b-fdc1e484cad1.png)
Dialog for multiple invalid elements for checkin - only pops open one dialog

Based on these findings, it doesn't seem like the multiple error dialogs are thrown if there are multiple invalid elements in the selection. Should we continue using the pattern that if at least one is valid, command is enabled?

**Comment by KristinaTaylor** [comment]
Sounds good. Based on that behaviour, I don't think we necessarily even need to document the specifics of each case, either - just that it's enabled if it is a valid operation for any in the selection.

**Comment by bleskows** [comment]
All right, I'll work with that then

**Comment by bleskows** [comment]
I am probably going to add more changes to this task, specifically options for si add. @KristinaTaylor, need your feedback on this, Chris brought this up and it seems we should also be specifying 
--createSubprojects and possibly --createSubprojectsForEmptyDorectories as well. Currently, I use neither options, so if you try to add a file in a folder, we'll get a folder in the project, and I believe there is discussion about moving away from that in the future.

**Comment by KristinaTaylor** [comment]
@bleskowskyPTC That's a good point. ~~Yes to createSubprojects, for sure.~~ (crossed out, per discussion at the coffee machine. ;) Follow the client preferences)

Because move also has a "createSubprojects" option, I'm reminded that we should also expose Move and Rename, here, since we don't really want to encourage use of the Windows actions, because Integrity will see the windows gestures as an add and a drop.

**Comment by bleskows** [comment]
Should we add Move and Rename to the commands required for this issue to be completed?

**Comment by KristinaTaylor** [comment]
Posted separately - #83

**Comment by bleskows** [comment]
@KristinaTaylor Just verified, createSubprojects option is not available in the Create Archive dialog that is opened on add. However, this is naturally configurable through si viewprefs. So as per our discussion, it makes sense to leave that option to the user's prefs? If so, then this can be verified using [1.0.89.0](https://ci.appveyor.com/project/PTC-ALM/tortoisesi/build/1.0.89.0) or later

**Comment by bleskows** [comment]
Can be verified using [1.0.89.0](https://ci.appveyor.com/project/PTC-ALM/tortoisesi/build/1.0.89.0) or later

**Comment by sharonzhao** [comment]
Using build 1.0.112.0, tested all 22 test cases that are in the heading 5 (File-based Operations) of test suite 1012724.

**Comment by KristinaTaylor** [comment]
Reviewed in demo.

**Comment by bleskows** [comment]
Removed needs docs: documented in Alpha release User Guide
