### ISSUE TITLE
Error message shows up when right clicked on a folder inside a sandbox

### ISSUE THREAD

**Issue by krrish1008** [PTC-ALM/TortoiseSI#180]
When there is no connection to the server, both of the following error shows up when right clicked on a folder in a sandbox directory

![error1](https://cloud.githubusercontent.com/assets/8945681/10495385/971d75e8-7289-11e5-90be-cf2df13b8b1e.PNG)
![error2](https://cloud.githubusercontent.com/assets/8945681/10495387/9b043228-7289-11e5-882e-a652a798fcfa.PNG)

**Comment by sharonzhao** [comment]
Tested on build 230 that the error didn't occur anymore when right clicked on a folder inside a sandbox directory without client connection .

This issue can be closed.

**Comment by KristinaTaylor** [comment]
Closing per testing notes.
