### ISSUE TITLE
Resynchronize on a folder does not work as expected

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#185]
When a user selects a folder in windows explorer and chooses TortoiseSI -> Resynchronize, the contents of the folder are not resynchronized.

It looks as if "si resync -sandbox <path>" is executed in this scenario, and silently errors without giving the user an option to recurse into the folder. The correct command execution will have to be investigated and arguments/command updated (possibly --cwd is required).

From RFC 1095161.

**Comment by krrish1008** [comment]
The "--sandbox" command option would have worked but in the MenuInfo where the sandbox name was being passed, there it was returning an empty string for the sandbox which avaided the action to even execute. when i tried to get the sandbox name initialized correctly, it worked. but i have still changed it to "--cwd" command option as its more efficient.

**Comment by sharonzhao** [comment]
Resynchronize on a folder is working properly. It resynchronizes everything in the folder. Tested with build 240.

This issue can be closed.

**Comment by KristinaTaylor** [comment]
Closing per testing notes. This will be included in the 1.1 release, when it's ready.
