### ISSUE TITLE
Update images in the installer

### ISSUE THREAD

**Issue by gisraeli** [PTC-ALM/TortoiseSI#19]
The installer still has Tortoise git images, this will need to be updated. All the these resources are located in <repo root>/src/TortoiseSISetup/include/

**Comment by KristinaTaylor** [comment]
![bagckground](https://cloud.githubusercontent.com/assets/10520385/6447838/bfafba96-c0e3-11e4-819b-1666ac27fb08.png)
![banner](https://cloud.githubusercontent.com/assets/10520385/6447841/c9567f9e-c0e3-11e4-9515-65fc89bb4424.png)
![tortoise_16x](https://cloud.githubusercontent.com/assets/10520385/6447864/f187fe20-c0e3-11e4-87ef-edad2338abeb.png)
![tortoise_32x](https://cloud.githubusercontent.com/assets/10520385/6447863/f187b4ec-c0e3-11e4-8107-e4de5e15e9f5.png)
![tortoise_48x](https://cloud.githubusercontent.com/assets/10520385/6447865/f18977b4-c0e3-11e4-9add-cd4e5be03650.png)
![tortoise_128x](https://cloud.githubusercontent.com/assets/10520385/6447862/f1867640-c0e3-11e4-9b61-7706d260c776.png)

I've got some .ico files, too, for wherever they're needed, but they can't be attached to issues apparently.

**Comment by bleskows** [comment]
I have been having issues getting the Wix installer to use pngs (although from what I can tell, this file format _should_ be supported). Using pngs, they don't show up in the installer. Converted them to jpgs and they show up fine (sans some tweaking that will need to be done for text spacing). Thoughts @KristinaTaylor ?

**Comment by bleskows** [comment]
![image](https://cloud.githubusercontent.com/assets/10633761/6449861/e727b188-c0f1-11e4-9d30-584502651553.png)
Note that I also will have to tweak some of the dialog descriptions (i.e. move them down) so that they don't overlap with the background (screen cap for reference). Not sure if I'm too thrilled with the new spacing though

**Comment by KristinaTaylor** [comment]
JPGs are fine, from my perspective.

The contractor who provides the images requested screen caps of them in context, so I think we can have him tweak it if necessary. Could you get me one of the license agreement page, too?

**Comment by bleskows** [comment]
![image](https://cloud.githubusercontent.com/assets/10633761/6451249/48bc9900-c0fb-11e4-8f84-00f7d50facdd.png)
License agreement dialog

**Comment by bleskows** [comment]
Do you think it's worthwhile for the contractor to tweak the banners? Those are the only ones that have the spacing issues. The background is fine:
![image](https://cloud.githubusercontent.com/assets/10633761/6451299/9c282e10-c0fb-11e4-9df3-c5b50fa3f206.png)

**Comment by KristinaTaylor** [comment]
Here's the updated banner. I'll email it, too.
![banner](https://cloud.githubusercontent.com/assets/10520385/6455886/3e8430e2-c128-11e4-928d-a7477fc2704a.jpg)

He's also (quite rightly, I think) suggested rewording to be less awkward. How about we change this to "Choose an install location and features."

**Comment by KristinaTaylor** [comment]
Also, how possible would it be to update the installer program's icon in the top left corner?

**Comment by bleskows** [comment]
![image](https://cloud.githubusercontent.com/assets/10633761/6465286/2923a00a-c18e-11e4-9caa-b8dde5d89297.png)

These are the main dialogs that I am re-wording. I may shorten a few more that may have spacing issues as well, but it's not as easy to get screenshots of them as they don't follow the ideal installation progression. Feedback @KristinaTaylor ?

Also, regarding the icon in the top left, if it is possible to change, which icon would you like? The tortoise.ico?

**Comment by bleskows** [comment]
Regarding to icon in top left, did some quick research and I don't think it's possible to do this. Apparently Windows Installer doesn't allow us to change the msiexec icon. See the following [message exchange](http://sourceforge.net/p/wix/mailman/message/15231661/)

**Comment by KristinaTaylor** [comment]
For the last one, I'd go for "Required Disk Space." Other than that, this looks great and I trust your judgement on the other ones. I may review the text resource bundles prior to release, but this looks much better.  Thanks!

**Comment by bleskows** [comment]
What will we be doing for updating the EULA (since that's apparently part of this task)? Right now, there's an rtf file sitting under TortoiseSI\src\TortoiseSISetup\include with the TortoiseGit info.

**Comment by KristinaTaylor** [comment]
I'm on an active thread with the legal department on that one. I'll let you know as soon as I have updated text. The one in there is copyrighted, so unless we leave the copyright in place, we need new text.

**Comment by bleskows** [comment]
Should we leave that for a separate task, or should I just check in what I have now and keep the task open until we have a new EULA?

**Comment by KristinaTaylor** [comment]
Check in what you have and leave the task open - I expect to have content in the next couple of days. If not, I'll split it out.

**Comment by bleskows** [comment]
I merged in PR #70. This PR only added the images to source control and modified the installer (images and some dialog strings). The EULA will be updated in a separate pull request once we have it. I'll add the needs verification flag for now, so that we can at least do whatever level of testing is appropriate for this (sanity, and make sure the installer still works), but we'll likely keep this issue open until we can check in the updated EULA as well. Build [1.0.68.0](https://ci.appveyor.com/project/PTC-ALM/tortoisesi/build/1.0.68.0) can be used for this verification. Verification should include that TortoiseSI images are shown correctly and that strings look sane.

**Comment by KristinaTaylor** [comment]
Split out the EULA task to task #74. This one can be closed when it is verified.

**Comment by sharonzhao** [comment]
Verified with build 1.0.72.0:
Tortoise SI images are shown correctly and the strings look good in the setup wizard.

**Comment by KristinaTaylor** [comment]
Reviewed during sprint review.
