### ISSUE TITLE
Overlay Icons like in any other Tortoise VCS client

### ISSUE THREAD

**Issue by lordyavin** [PTC-ALM/TortoiseSI#194]
Please provide overlay icons to decorate files and folders in a sandbox. This is a common and the most useful feature of an explorer extension.

<img src="https://tortoisesvn.net/assets/img/Overlays.65cd6215.png" />

**Comment by lordyavin** [comment]
It works. Don't know why I didn't see the icons.

**Comment by KristinaTaylor** [comment]
There are a number of reasons why they might not appear, but the most common is that Windows just hasn't repainted the files. The simplest way to force Windows to repaint them is to reboot. :)
