### ISSUE TITLE
Replace all "SVN" texts with "SI"

### ISSUE THREAD

**Issue by lordyavin** [PTC-ALM/TortoiseSI#195]
Some Dialogs still show text that contains "SVN". Please replace all "SVN" with "SI". BTW: What das SI mean?

**Comment by KristinaTaylor** [comment]
Could you please post any specific examples? This project was forked from TortoiseGit, which was forked from TortoiseSVN, which was forked from TortoiseCVS, so the code has a long legacy. Many dialogs and much of the code that exists in the project hasn't been exposed in the TortoiseSI menus and commands. We should definitely clean up any that are exposed, though.

SI is the command line interface for interacting with the configuration management capabilities of PTC Integrity Lifecycle Manager. We used this in the project name to be consistent with things like TortoiseSVN, were svn is the command line interface for interacting with subversion.

**Comment by lordyavin** [comment]
Damn, I can't find the dialog again. Sorry

**Comment by KristinaTaylor** [comment]
No problem! I'll close this for now, but feel free to re-open or create a new one when you have details.
