### ISSUE TITLE
Please tell me about TortoiseSI User Guide.

### ISSUE THREAD

**Issue by nshige** [PTC-ALM/TortoiseSI#197]
The version of the Installer of shown TortoiseSI is "1.0.230.0".
In contrast, the TortoiseSI User Guide is listed with "TortoiseSI 1.0".
Because a version does not accord with an Installer in User Guides, I do not know whether a User Guide is equivalent to TortoiseSI of which version.

In addition, a right-click menu does not accord with the function of the TortoiseSI User Guide.
For example, I am listed in TortoiseSI User Guide with "Resynchronize a Folder", but the right-click menu becomes "Resynchronize".
From this, it is thought that there are not an Installer and the version of the TortoiseSI User Guide.

Which version of TortoiseSI is TortoiseSI User Guide a listed thing for?

Please show me a method to identify an applicable version of TortoiseSI from TortoiseSI User Guide.

**Comment by vichavan-PTC** [comment]
The user guide belongs to the same installer version 1.0.230.0.  If the numbering is causing confusion, we will update the user guide to reflect the latest installer version.

Regarding 'Resynchronize a Folder', please note that 'Resynchronize a Folder' is the Member operation (as indicated in the column header) and 'Resynchronize' is the actual command. Refer last column in the same table which displays the actual command.

**Comment by nshige** [comment]
Thank you for an answer.
I understood the contents which had you reply it.

In addition, I had you list a detailed version in TortoiseSI user guide and was saved very much.

I was able to cancel an ignorance point.
This Issue closes it.
