### ISSUE TITLE
Please tell me the public timing of the TortoiseSI installer.

### ISSUE THREAD

**Issue by nshige** [PTC-ALM/TortoiseSI#198]
The installer of the URL is the recognition called the latest installer as follows.
<https://ptc-alm.github.io/TortoiseSI/>

On the other hand, with the cord of GitHub, the version that is newer than an installer seems to be released.
Therefore it is a question, but please show me it what kind of timing the installer of TortoiseSI is shown in.
I think that it is either following.
　①The version of the installer is updated when performance guarantee was completed.
　②The user who wants to use TortoiseSI obtains a cord released individually in Github and I build and use it.

②Is the recognition called the performance guarantee finished all right for の case, the cord which has been released?

In addition, will the TortoiseSI user manual corresponding to the cord of TortoiseSI exist?
If the manual corresponding to the cord of each version exists, please show me the location and a specific method.

**Comment by vichavan-PTC** [comment]
If I understand your concern correctly, you are trying to compare the TortoiseSI build with the builds available in appveyor? If that is the case, then the TortoiseSI build which is mention in the user documentation is the latest one (1.0.230.0) The builds in appveyor are development builds, you should ignore it.
