### ISSUE TITLE
Please tell me the version of Windows that TortoiseSI supports.

### ISSUE THREAD

**Issue by nshige** [PTC-ALM/TortoiseSI#199]
A version of Windows for the support is not written to TortoiseSI user guide.
I want to know the version of Windows that TortoiseSI supports.
Therefore please tell me the version of Windows that TortoiseSI supports.

I installed TortoiseSI in Windows7 and Windows10.
a blue plus sign is displayed in Windows7 by the member who added it.
However, a red exclamation mark icon is displayed in Windows10 by the member who added it.

Besides, the icon of the member who excluded it becomes a red X icon in Windows7.
However, a red X icon is not displayed in Windows10.

From the above-mentioned result, I think that TortoiseSI may not support Windows10.

**Comment by vichavan-PTC** [comment]
Yes, you are right, TortoiseSI is not supported on Windows 10. We will update the documentation to explicitly mention that.

**Comment by nshige** [comment]
Do you plan to support Windows 10?
Please let me know when Windows 10 will be supported.

**Comment by vichavan-PTC** [comment]
We would definitely like to update the support to Windows 10, but we cannot plan it in the next one year as we have other priorities. Since this is an open source project, we would like to see contribution from outside of PTC though to help expand this support.
