### ISSUE TITLE
"Drop Sub-Project" command is not written in the TortoiseSI user guide.

### ISSUE THREAD

**Issue by nshige** [PTC-ALM/TortoiseSI#200]
"Drop Sub-Project" command which is not written in the TortoiseSI user guide is displayed in the right-click menu of the folder.
Since the "Drop Sub-Project" command works, please describe it in the TortoiseSI user guide.

**Comment by vichavan-PTC** [comment]
The documentation will be updated.

**Comment by nshige** [comment]
Please correct TortoiseSI user guide.

After adding a pull request or modifying the document, I want you to close Issue.
If you do not do it, I do not understand Issue's correspondence situation.
