### ISSUE TITLE
"View Sandbox" and "Related Change Packages" are not displayed when files are selected.

### ISSUE THREAD

**Issue by nshige** [PTC-ALM/TortoiseSI#201]
In the TortoiseSI user guide's "View Sandbox", it says "Select a file or a folder in a project." And I believe that you can use "View Sandbox" with files selected.
However, "View Sandbox" will not be displayed even if you right-click with the file selected.

Likewise, "Related Change Packages" is also written as "Select a file, folder, or subfolder in a project." In the TortoiseSI user guide.
However, "Related Change Packages" does not appear even if you right-click with the file selected.

Which is TortoiseSI's behavior or the TortoiseSI user guide correct?

**Comment by vichavan-PTC** [comment]
The user guide seems to be updated incorrectly. This implementation was not complete and not available for File (Members). The user documentation will be updated soon.

**Comment by nshige** [comment]
Please correct TortoiseSI user guide.

After adding a pull request or modifying the document, I want you to close Issue.
If you do not do it, I do not understand Issue's correspondence situation.
