### ISSUE TITLE
Please tell me the behavior of the overlay icon.

### ISSUE THREAD

**Issue by nshige** [PTC-ALM/TortoiseSI#202]
Overlay icons are recognized as 15, due to Windows registry restrictions.
When the number of registered overlay icons exceeds 15,
Is it okay to recognize that the TortoiseSI overlay icon is not displayed?

TortoiseSVN recognizes that overlay icons of other applications will be prioritized when the number of registered overlay icons exceeds 15.
Is TortoiseSI overlay icon behavior the same as TortoiseSVN?

**Comment by nshige** [comment]
If the icon overlay exceeds 15, what kind of priority will the TortoiseSI icons be displayed?
Especially, please tell me the behavior of the part where "Limited File Icon Overlay Subset" of TortoiseSI user guide is "N / A".

"ShellIconOverlayIdentifiers" Is it displayed with the priority of 1 to 9 registered in the registry?
Or are you deciding the display priority of overlay icon with TortoiseSI?
If you decide the icon overlay display priority with TortoiseSI, please tell us the priority.

**Comment by vichavan-PTC** [comment]
The overlay icon behaviour is basically driven by the Windows, so all restrictions applied by Windows are valid here.
Refer Notes section in user documentation for icon overlays - In cases where other file system-based integrations limit the number of icon overlays available to TortoiseSI, a limited subset of icons appear instead, as defined in Limited Icon Overlay Subset column in the Integrity Member Status table.
