### ISSUE TITLE
Please tell me about the behavior of the folder icon.

### ISSUE THREAD

**Issue by nshige** [PTC-ALM/TortoiseSI#203]
I have confirmed the operation with Windows 7, Integrity 10.9, TortoiseSI Ver 1.0.230.0.
Immediately after creating a new folder on Windows Explorer, a green check icon will be displayed in that folder.
According to the TortoiseSI user guide I think that it is a condition to become a blue + icon.

Also, if I do "Drop Sub-Projecct" for a folder, it will not be a red × icon,
It remains a green check icon.

I believe that the above behavior and Issue # 108 from TortoiseSI are not yet fully supported for folder icon overlay.
Is there any recognition of me?

If it corresponds to folder icon overlay, please tell me the display condition of each icon overlay of the folder.
· Add: A blue plus Icon
· Drop: A red X icon
· Member: A green checkbox icon
· Locked: A yellow lock icon
· Modified, Moved, Renamed: A red exclamation mark icon
· Conflict: A yellow exclamation mark icon

In the environment that I confirmed the operation, the number of "ShellIconOverlayIdentifieres" registered is within the limit value.
*Operate the registry and delete the registry registered by the system so that it is within the limit value.

**Comment by vichavan-PTC** [comment]
You are right, issue 108 is still Open. We have not fixed it. 

Also refer comments in Issue#108 - If you would like to contribute to the design of this feature, please feel free to comment here, or in the PTC user community, at: https://www.ptcusercommunity.com/thread/124495
