### ISSUE TITLE
When is the new version of TortoiseSI installer available?

### ISSUE THREAD

**Issue by nshige** [PTC-ALM/TortoiseSI#204]
It is about the answer of Issue # 198.
[https://github.com/PTC-ALM/TortoiseSI/issues/198](url)

I am watching GitHub's Releases.
GitHub's Releases have version 1.8.16.0 at 2017/4/24.

Also, since the following Issue is closed, I think that there is Ver1.1 source code.
[https://github.com/PTC-ALM/TortoiseSI/issues/185](url)

Therefore, I want to know the release timing of the new version of TortoiseSI installer.

**Comment by vichavan-PTC** [comment]
Hi, unfortunately, we have not planned the next release/version of TotoiseSI as yet. We will let you know once we plan for it. For now, the version mentioned in the documentation is the latest supported/release version by PTC.
