### ISSUE TITLE
Please correct TortoiseSI user guide.

### ISSUE THREAD

**Issue by nshige** [PTC-ALM/TortoiseSI#205]
It is supposed to fix the document with the answer of Issue # 200, # 201.
[Https://github.com/PTC-ALM/TortoiseSI/issues/200](url)
[Https://github.com/PTC-ALM/TortoiseSI/issues/201](url)

Please correct TortoiseSI user guide.

**Comment by nshige** [comment]
After adding a pull request or modifying the document, I want you to close Issue.
If you do not do it, I do not understand Issue's correspondence situation.

**Comment by anuragsen** [comment]
Updated the user guide to resolve issue 200 and 201
