### ISSUE TITLE
Take a look at "doc" directory for usefulness

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#22]

**Comment by kevinpwatson** [comment]
Most of the documentation is on Git and Git actions, but there are a couple sections that might be useful:
1. Introduction (installation, features, language packs)
2.1 Getting Started (icons, context menus, shortcuts)
2.6 Getting Status Information (icon overlays, status)
2.35 Settings (not sure if this will be part of TortoiseSI or what settings there would be)

Also, we might want to keep the same type of documentation order/structure.

I've built the TortoiseGit docs as HTML, zipped them up and put them here:
ftp://ftp.mks.com/Services/docs/TortoiseGit_en.zip
Double-click index.html to view.

You can also view them online here: http://tortoisegit.org/docs/tortoisegit/
