### ISSUE TITLE
Further cleaning up of Tortoise content

### ISSUE THREAD

**Issue by gisraeli** [PTC-ALM/TortoiseSI#23]
To be done soon, or posted as it's own issue:
- ~~figure out whether the installer warnings about " duplicate sequence number" are a concern~~ done in pull request #29
- ~~make CrashReporter do something or get rid of it~~ done in pull request #29
- what does the "class ids" comment in Guids.h refer to? -->?asnwered: these where the tortoise SVN class ids
- ~~remove unneeded code from ShellCache~~ all removed in #46
- ~~update Integrity API with stuff from build that has Blaise's changes~~ moved to #40
- ~~add registry key to enable api logging?~~ moved to #39
- ~~give root folder cache need a faster search than linear (ie binary? or some sort of tree...)~~ replaced with #56
- ~~is the PathIsDirectoryW too expensive to be done from  CShellExt::IsMemberOf_Wrap?~~ moved to #42
- ~~do we still want to implement ICopyHook?~~ removed in c20dbe6
- ~~do we need the drag and drop stuff?~~ removed in d770703
- ~~remove win 7 library / folder support~~ removed in c20dbe6
- ~~clean up the ext tree~~ done in #46
- ~~get rid of the custom install actions dll if we don't need it~~ done in #46
- ~~make sure no installed client is handled gracefully~~ moved to #41
- update or remove the following files
  - ~~/build.txt    - /release.txt    - /.tgitconfig    - /.mailmap    - /.gitmodules    - /src/Changelog.txt    - /src/Changelog-pre1.8.txt    - /src/Debug-Hints.txt    - /src/TortoiseShell/*.reg~~ all removed in #46 
- ~~remove installer UI customisation~~ moved to #57

**Comment by KristinaTaylor** [comment]
All issues have been addressed or moved to other issues.
