### ISSUE TITLE
Make AppVeyor failure notifications/emails more meaningful

### ISSUE THREAD

**Issue by bleskows** [PTC-ALM/TortoiseSI#26]

**Comment by KristinaTaylor** [comment]
Build issue. Assigning to Blaise.

**Comment by bleskows** [comment]
@KristinaTaylor
Do you have any suggestions for any rules we could try to enforce on this? For example, the current setup is to email everyone on the list whenever a build kicks off. I can look into setting up rules such as: only email committer. For something more complicated, I would have to do a bit more research since the AppVeyor docs seem rather limited in terms of email notification setup.

For the purposes of a small team (for the time being), probably emailing everyone is sufficient. If you had any thoughts on this, let me know.

**Comment by KristinaTaylor** [comment]
I can see a few different use cases for these emails, and I don't know how configurable it is, so none of these are strict requirements - do what can be done, really:
1. Add a link to the build artifact, if the build passed.
2. Add a link to the build log, if the build failed.
3. Add information about which branch or pull request got built.

Nice to have:
4. Only send failure & success notifications if it's building "master"?
5. Only send failure notifications to the person whose branch it is?

Just some ideas.

**Comment by bleskows** [comment]
The email formatting (1-3) seems most important so I'll work on that. I'll see if I can provide a solution for 4 and 5.

**Comment by bleskows** [comment]
In PR #27, the current (default) email template provides a link to the AppVeyor build page.
As per Kristina's comments, I feel that the basic template satisfies the requirements:
1. Add a link to the build artifact, if the build passed. _Email indicates complete/fail and provides link to the AppVeyor build page where artifacts easily accessible_
2. Add a link to the build log, if the build failed. _Email indicates complete/fail and provides link to the AppVeyor build page where build log easily accessible_
3. Add information about which branch or pull request got built. _AppVeyor build page shows whether a pull request was built or what branch was built_
4. Only send failure & success notifications if it's building "master"? _Currently, appveyor.yml is configured to only build master branch_
5. Only send failure notifications to the person whose branch it is? _This is a tricky one. From what I've read on AppVeyor site, this is only really configurable on a per-user level in their Notification Configurations (only email for builds with my commits only). This is not easily configured through yml at this time_

@KristinaTaylor should this suffice? In which case, this PR could be merged into the master as soon as possible to prevent further build failures

**Comment by KristinaTaylor** [comment]
Looks good, from my perspective. :+1:

**Comment by sharonzhao** [comment]
Verified with build 1.0.8.0:
- Email notification sent to all relevant users.
- Complete build is indicated in the email with a link to the AppVeyor build page where artifacts easily accessible.
- Information about which branch or pull request got build is added. AppVeyor build page displays the information.

**Comment by sharonzhao** [comment]
Need an unsuccessful build to verify email notification, link, and build log of the failed build.

**Comment by bleskows** [comment]
I think the only way to verify this (short of checking in code to the master to break the build) would be to look at the results of a  failed build from a pull request, since it doesn't really matter whether the notification is for a master build or a PR build, just so long as it is sent. As of right now we don't have any PR fails to verify on.
