### ISSUE TITLE
Provide ability for a user to submit changes

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#30]
This issue will be split into multiple issues.

![submitcpmockup](https://cloud.githubusercontent.com/assets/10520385/6026300/a69ba3e0-aba7-11e4-898d-3b661fea00f4.png)

Change description would apply to the Change Package description, and each member/file operation would cause the existing Integrity Client dialogs to appear when user input is needed.

If the administrator has configured templates, the change description should be pre-populated with the template.

**Comment by KristinaTaylor** [comment]
Steps towards implementing this (will be split into separate issues):
- ~~Provide drop down of open change packages & Submit CP & Cancel buttons~~ (#75)
- ~~Results of wf changes command displayed in a table (list of modified files), grouped by change package, sortable within the grouping, and includes status & extension columns~~
- ~~Add warning icon & view CP button~~
- ~~Add create CP button.~~
- ~~Add description text box~~
- ~~Prepopulate description with change package template, if applicable~~
- ~~Add sticky select check box. This includes the dynamic behaviour~~ (#107)

**Comment by bleskows** [comment]
Removed needs docs: documented in Alpha release User Guide

**Comment by KristinaTaylor** [comment]
This has been split into issues #75 and #107
