### ISSUE TITLE
Allow TortoiseSI user to add things to Integrity Client preferences for non-members exclude file filter

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#31]
TortoiseSI should expose a gesture to "ignore" (exclude) a file (filename.txt) or a pattern (*.txt). Update internally, don't pop the dialog.

TortoiseGit has a "delete and ignore." We shouldn't do this, because Integrity doesn't follow that pattern, it only applies on new adds.

**Comment by gisraeli** [comment]
We still want to use the menus they auto generate for ignoring the file, ie for a foo.txt they auto generate foo.txt and *.txt options

**Comment by bleskows** [comment]
I'll look at this. Could someone assign me?

**Comment by gisraeli** [comment]
@bleskowskyPTC  done

**Comment by KristinaTaylor** [comment]
From Review: This should only apply to adds (non-members), not controlled files. Problem in fileinfo command.

**Comment by bleskows** [comment]
Submitted code for an Integrity defect that fixes the fileinfo command. Once that has been verified, the TortoiseSI integration can be re-verified as well. Anything later than [1.0.59.0](https://ci.appveyor.com/project/PTC-ALM/tortoisesi/build/1.0.59.0) should do.

**Comment by bleskows** [comment]
Re-verify using Integrity Client 7870 or later and Tortoise SI build [1.0.59.0](https://ci.appveyor.com/project/PTC-ALM/tortoisesi/build/1.0.59.0) or later

**Comment by sharonzhao** [comment]
Followed the following steps to verify, using Integrity Client 7874 and TortoiseSI build 1.0.64.0.
- Right click on a controlled file
- Go to Tortoise SI -> Add to exclude filter -> *.txt
- Add a text file (e.g. t1.txt) to the sandbox from windows explorer
- There's no status shown on the non-member file t1,txt
- Try to add t1.txt as a member to the sandbox in GUI
- Getting error: Some files from the selection were not added by the command. Individual file details are available below - C:\Sandboxes\t1.txt matches exclude filter

**Comment by sharonzhao** [comment]
Verified with build 1.0.72.0:
Now the Add to exclude filter option is available on the right click menu of non-members files.

**Comment by KristinaTaylor** [comment]
Reviewed during sprint review.

**Comment by bleskows** [comment]
Removed needs docs: documented in Alpha release User Guide
