### ISSUE TITLE
Create and View sandboxes

### ISSUE THREAD

**Issue by gisraeli** [PTC-ALM/TortoiseSI#32]
- view a sandbox for a folder that has a sandbox. Option should only be available for folders with sandboxes
- create sandbox for folder that does not yet have a top level sandbox

**Comment by gisraeli** [comment]
can be tested with 1.0.7.0, 1.0.8.0, 1.0.9.0

**Comment by KristinaTaylor** [comment]
We should use the "make files writeable" option when creating sandboxes from Windows Explorer, to make it easier for users to edit their files.

**Comment by KristinaTaylor** [comment]
@gisraeli could you add a note here that says which pull request has the code for this?

**Comment by gisraeli** [comment]
The "make files writeable" is a global / project policy not a sandbox option...

**Comment by gisraeli** [comment]
Question: when preventing the user from creating a sandbox in a folder that has descendant folder that are sandboxes I wasn't sure if it would be a good idea to just hide the menu item (since it may not be obvious to the user why this is not visible, instead I decided to enable it, and if they select this menu item show an error listing the existing sandbox locations.

(This does not apply to trying to create a sandbox inside an existing one, then the menu is just hidden)

**Comment by gisraeli** [comment]
This can be verified with build [1.0.13.0](https://ci.appveyor.com/project/PTC-ALM/tortoisesi/build/job/jb5xo20s9112h6yd/artifacts)

**Comment by gisraeli** [comment]
Things to verify:
- both options only available:
  - when a single folder is selected
  - when there is no selection (just clicking on the background of a folder)
  - not available when selecting multiple item (files, folders, etc)
- view sandbox available (and opens the appropriate sandbox view) if either the selected folder the current path / window has a sandbox
- create sandbox available (and creates the sandbox) if either the selected folder the current path / window has no sandbox
  - after the sandbox is created the folder should refresh on it's own to show the green check marks (no need to press F5)
  - if one (or more) of the children of the selected folder (or current folder) have a sandbox a dialog will pop up explaining to the user why we can't create a sandbox here and all the child (or grand child etc) locations that have a sandbox
    - if there are too many entries in this dialog this dialog should have a scroll bar

**Comment by sharonzhao** [comment]
Verified the following functionalities with build 1.0.13.0:
- Create Sandbox option is available from the right click menu when:
  1. A single folder is selected.
  2. There is no selection (just right clicking on the background of a folder)
- View Sandbox option is available from the right click menu when a single folder is selected.
- Neither the Create Sandbox nor the View Sandbox option is available when multiple items (files, folders, etc) are selected.
- View Sandbox option is available and opens the appropriate sandbox view if either the selected folder has the current path or window has a sandbox.
- Create sandbox option is available and creates the sandbox if either the selected folder has the current path or window has no sandbox:
  1. After the sandbox is created, the green checkmark shows on the folder without pressing F5.
  2. If one or more of the children of the selected folder (or current folder) have a sandbox, a dialog   pops up explaining to the user why we can't create a sandbox here and all the child (or grandchild etc) locations that have a sandbox are listed.

**Comment by sharonzhao** [comment]
Found two bugs when using build 1.0.13.0 to test create and view sandboxes. Posted issue #43 and #44.

**Comment by bleskows** [comment]
Removed needs docs: documented in Alpha release User Guide
