### ISSUE TITLE
Make sure installer allows upgrades

### ISSUE THREAD

**Issue by gisraeli** [PTC-ALM/TortoiseSI#33]
If you have version 1.0.X.0 of the integration 
- make sure that 1.0.(X+1).0 can be installed (it should automatically uninstall 1.0.X.0)
- trying to install 1.0.X.0 asks you Modify, Repair or Remove installation?
- trying to install 1.0.(X-1).0 is not allowed (tells you that a newer version is already installed)

**Comment by gisraeli** [comment]
can be tested with 1.0.7.0, 1.0.8.0, 1.0.9.0

**Comment by sharonzhao** [comment]
Tested the installer with build 1.0.8.0 and 1.0.9.0 (1.0.8.0 was installed before the following testing was performed):
- Installing 1.0.8.0 again - the installer asked to select one of the operations: Modify, Repair, or Remove installation.
- Installing 1.0.9.0 - the installer was successfully installed, and the old installer (version 1.0.8.0) was automatically uninstalled.
- Installing 1.0.8.0 again - the installer gave the warning message: "A later version of TortoiseSI 1.0.8.0 (64 bit) is already installed. Setup will now exit."
