### ISSUE TITLE
Update TortoiseSI's version of the C API with the "no logging" changes

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#40]
Split from #23 
Given that TortoiseSI integrates with explorer.exe, the working directory could be anywhere, a change was made in Integrity 10.7 that allows an integration to tell the C API not to drop log files in the integration's working directory. This has been done, so TortoiseSI needs to pick up a new version of the API.

**Comment by gisraeli** [comment]
I can't quite remember which build of Integrity @bleskowskyPTC 's changes went into but the API lib and headers any build after that will do.

**Comment by gisraeli** [comment]
in this repository the Integrity API lives under /ext/Integrity

**Comment by bleskows** [comment]
I think anything after Integrity Build 7805 should be fine.

**Comment by flemingg** [comment]
OK going to add libs, etc. from build 7852

**Comment by KristinaTaylor** [comment]
Closing during sprint review as a "build" task. Verified in Integrity 10.7.
