### ISSUE TITLE
If no Integrity client can be found, fail gracefully

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#41]
Split from #23. 
The Integration needs to gracefully handle the situation where there is no Integrity client found in the PATH:

Integration could pop up a dialog (or system tray notification) to inform the user that they need an Integrity client installed, in order to use TortoiseSI. At this time, it would set a registry key to prevent this from appearing again. This registry key would be cleared if we find the client again. This registry key needs a mutex to protect it, following the pattern established by the connection handling.

Registry key must be documented [here](https://github.com/PTC-ALM/TortoiseSI/wiki/Registry-Keys-Used-by-TortoiseSI).

**Comment by KristinaTaylor** [comment]
Handle scenario when there is no client in the PATH:
Integration pops a dialog (or system tray notification) to inform the user that they need an integrity client in order to use TortoiseSI. Registry key gets set to prevent this from appearing again. This registry key could be cleared if we find the client again. Registry key needs a mutex to protect it.

**Comment by atusek** [comment]
If an Integrity client cannot be found in the PATH, the TortoiseSI context menu does not appear.

However, if the Integrity client is uninstalled after TortoiseSI has been loaded in the explorer.exe process space, the context menu will continue to appear until the explorer.exe process is restarted (manually or via a reboot). If the user attempts an operation, a client communication error will appear:

![image](https://cloud.githubusercontent.com/assets/6186615/9945356/d1ad1fea-5d5a-11e5-9d43-12da7d5463eb.png)

Error dialog will continue to appear every time TortoiseSI attempts to establish a connection to the client. User has the option to suppress the dialog by selecting "In the future, do not show me this dialog box". This will create a registry entry that is documented on the [wiki page](https://github.com/PTC-ALM/TortoiseSI/wiki/Registry-Keys-Used-by-TortoiseSI).

**Comment by sharonzhao** [comment]
Verified on build 210 that the Integration gracefully handled the situation where there is no Integrity client found in the PATH. 

This issue can be closed.

**Comment by KristinaTaylor** [comment]
Closing based on testing notes above.
