### ISSUE TITLE
Clarify the types of File System locations that won't be covered by TortoiseSI

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#42]
From issue #23 : "is the PathIsDirectoryW too expensive to be done from CShellExt::IsMemberOf_Wrap?"

We need to implement changes to prevent TortoiseSI from being enabled in certain types of file system locations.
This will include:
- network drives
- removable drives

**Comment by gisraeli** [comment]
The only types of drives that TortoiseSI will show status on is fixed local dirves. Other drives like ram drives, CD roms, floppy drives, network shares, remote drives, etc will not have any status or menu options available

**Comment by gisraeli** [comment]
this is implemented in pull request #46

**Comment by bleskows** [comment]
Verified with build 1.0.20.0:
- TortoiseSI->Create sandbox is available in a fixed local drive. Shows status on a sandbox in a local fixed drive.
- TortoiseSI->Create sandbox is not available when right-clicking DVD drive.
- TortoiseSI->Create sandbox is not available in a network drive (i.e. shared folder).

**Comment by KristinaTaylor** [comment]
Flagged with needs verification so that test cases can be added to the TortoiseSI regression testing suite.

**Comment by bleskows** [comment]
Added two test cases to the test suite.

**Comment by KristinaTaylor** [comment]
Reviewed & closed.

**Comment by bleskows** [comment]
Removed needs docs: documented in Alpha release User Guide
