### ISSUE TITLE
Newly created folders that are not inside a sandbox should not show status (green checkmark).

### ISSUE THREAD

**Issue by sharonzhao** [PTC-ALM/TortoiseSI#43]
I had a folder (0209s4) which is not a sandbox. I created a couple of folders (f1, f2, f3, f4, f5, f6, f7, f8, f9) inside it, and some of them (f1, f2, f3, f4, f5) are sandboxes. Green checkmark show on folders which are sandboxes. Then I created more folders f10, f11, f12, They are not sandboxes, but green checkmark show on these folders. 

Below is the output of wf folders:
C:\Integrity\IntegrityClient10\bin>mksapiviewer --iplocal wf folders
Response:
  App. Name    = wf
  Command Name = folders
  Work Item:
    Id         = c:\sandbox\0209s3
    Context    = NULL
    Model Type = si.Folder
  Work Item:
    Id         = c:\sandbox\0209s4\f1
    Context    = NULL
    Model Type = si.Folder
  Work Item:
    Id         = c:\sandbox\0209s4\f2
    Context    = NULL
    Model Type = si.Folder
  Work Item:
    Id         = c:\sandbox\0209s4\f3
    Context    = NULL
    Model Type = si.Folder
  Work Item:
    Id         = c:\sandbox\0209s4\f4
    Context    = NULL
    Model Type = si.Folder
  Work Item:
    Id         = c:\sandbox\0209s4\f5
    Context    = NULL
    Model Type = si.Folder
  Exit Code    = 0

Screenshot to be attached.

**Comment by sharonzhao** [comment]
![newly created folders show green checkmark](https://cloud.githubusercontent.com/assets/10675313/6114836/db008c4c-b06e-11e4-940b-305354b26336.jpg)

**Comment by gisraeli** [comment]
As Kristina pointed out this basically a sub string bug. See RootFolderCache::isPathControlled

**Comment by gisraeli** [comment]
can be verified with build [1.0.30.0](https://ci.appveyor.com/project/PTC-ALM/tortoisesi/build/1.0.30.0)

**Comment by KristinaTaylor** [comment]
Reviewed during sprint review. Test cases have been added.
