### ISSUE TITLE
Scroll bar is missing on the error dialog

### ISSUE THREAD

**Issue by sharonzhao** [PTC-ALM/TortoiseSI#44]
When sandbox cannot be created, user gets error message in a dialog. There is no scroll bar even when there are many entries in the dialog.
![scroll bar on the error dialog does not show up even when there are too many entries](https://cloud.githubusercontent.com/assets/10675313/6117575/794222da-b083-11e4-8fab-0959b1e4411a.jpg)

**Comment by KristinaTaylor** [comment]
This also needs a spellcheck: "becase" -> "because"

**Comment by gisraeli** [comment]
I thought that there was a scroll bar that came with MessageBox or MessageBoxEx. If not we should just truncate the list at some reasonable number.

**Comment by sharonzhao** [comment]
Verified with build 1.0.36.0:
The error dialog shows a maximum sandbox paths when there are many entries in the dialog:
![error dialog shows a maximum sandbox paths](https://cloud.githubusercontent.com/assets/10675313/6272385/24f35528-b835-11e4-8f96-e7789a9b7de6.jpg)

**Comment by sharonzhao** [comment]
The typo "becase" has also been fixed. Now it's "because".

**Comment by KristinaTaylor** [comment]
Reviewed during sprint review - @sharonzhao has confirmed that test cases have been added to the appropriate test suite.
