### ISSUE TITLE
Create a project page for TortoiseSI

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#45]
We need to create a GitHub Project page for TortoiseSI. This project page should include an appropriate location to check in HTML content for the user documentation.

**Comment by kevinpwatson** [comment]
For creating GitHub Pages there are two options: 

**Automatic Page Generator**
- Found in the repository Settings, so need to be an Owner or Admin to access it.
- Allows the editing of the content area of one page (home page) through a web browser and GitHub Markdown.
- Can pick from some pre-made themes/templates.
- Can clone the repository ("gh-pages" branch) to make changes to files or add files.  Could add the docs html files and images.
- Files used in the template get overwritten when updating using the "Automatic page generator" method.  Usually it is just the main "index.html" page, unless you switch templates.  No manually added files or folders get deleted or overwritten when updates are made.  If the "index.html" file is manually updated, those changes do not appear in the web and will be overwritten when saved. 
- If there is an acceptable theme, we could initially create the site using the Automatic page generator, and then update manually (never using the Automatic page generator again).

**Manual Creation**
- Create a "gh-pages" orphaned branch.
- Push html pages and web files to the gh-pages branch.
- Would need to create the site manually or in some tool and then push it all up.

Both methods end up with a "gh-pages" branch to store the site files.  This is where GitHub looks for project site pages.

Project sites are accessed by: http://username.github.io/projectname
So, ours would be: http://PTC-ALM.github.io/TortoiseSI/

We could point the tortoisesi.org domain to the GitHub site.

**Comment by KristinaTaylor** [comment]
Reviewed in Sprint review - starting point looks great!
