### ISSUE TITLE
Merge code for sandbox status

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#5]
Must be able to:
- tell that a file system folder corresponds to a sandbox.
- ~~launch an Integrity sandbox view from a folder that corresponds to a sandbox.~~ moved to #32
- force the status on a folder to be updated. 

~~View sandbox gesture should not be available on any folder that is not in a sandbox.~~ moved to #32

**Comment by gisraeli** [comment]
code for this was merged into master in pull requests #28 and #29

**Comment by gisraeli** [comment]
can be verified in build 1.0.8.0 or newer

**Comment by gisraeli** [comment]
Make sure that any folder inside a sanbdox has a green checkmark. make sure that if you have a folder open and you drop the sandbox (or create a new one) then the greencheck marks go away or become visible (depending on your action) after you press F5.

**Comment by sharonzhao** [comment]
Tested using build 1.0.9.0 - folder inside a sandbox didn't show the status (a green checkmark).

**Comment by gisraeli** [comment]
seems to be a stub dll loading issue

**Comment by gisraeli** [comment]
fixed in pull request #37

**Comment by gisraeli** [comment]
can be tested using [build 1.0.11.0](https://ci.appveyor.com/project/PTC-ALM/tortoisesi/build/1.0.11.0/job/gy71x3ioi86q3065/artifacts)

**Comment by sharonzhao** [comment]
Tested the sandbox status with build 1.0.11.0. 
Steps:
- Have a folder inside a sandbox
- Install the installer from the latest build (1.0.11.0)
- Reboot the machine
- Reopen windows explorer
- Go to the folder that is inside the sandbox
  Result:
  The folder and the sandbox had a green checkmark on it. 

Also verified that the following features:
- Dropping the sandbox that created from the above steps made the green checkmark on the sandbox and the folder go away after the machine was restarted.
- Creating a new sandbox that contains a folder made the green checkmark show on both the sandbox and the folder.

**Comment by sharonzhao** [comment]
Need to post a new issue to fix the machine need to be restarted problem.
After the installer is installed, the sandbox and the folder inside it should show the green checkmark without restart of the machine. It is the same problem as when dropping the sandbox. The green checkmark should disappear without restart of the machine.

**Comment by gisraeli** [comment]
The restart issue should be fixed in pull request #38

**Comment by gisraeli** [comment]
The restart issue should be fixed in build [1.0.13.0](https://ci.appveyor.com/project/PTC-ALM/tortoisesi/build/job/jb5xo20s9112h6yd/artifacts)

**Comment by sharonzhao** [comment]
Tested with build 1.0.13.0:
I had a folder open, and when I dropped the sandbox, the green checkmark disappeared after pressing F5. No longer need to restart the machine.
