### ISSUE TITLE
Error when creating sandbox

### ISSUE THREAD

**Issue by sharonzhao** [PTC-ALM/TortoiseSI#54]
Found this bug in our sprint review.
Right click menu -> Create Sandbox gets the error:
![error creating sandbox](https://cloud.githubusercontent.com/assets/10675313/6272638/3184eebc-b837-11e4-9049-0943c671450a.jpg)

**Comment by flemingg** [comment]
Fix is in pull request #55

**Comment by sharonzhao** [comment]
Still getting the same error in build 1.0.38.0.

**Comment by atusek** [comment]
Verified with the following steps:

![createsandbox1](https://cloud.githubusercontent.com/assets/6186615/6352759/081031ec-bc13-11e4-9c27-2ecc8915fc01.jpg)

Create sandbox wizard invoked and sandbox created:

![createsandboxwizard1](https://cloud.githubusercontent.com/assets/6186615/6352773/1eee7996-bc13-11e4-8e75-c041e26173a5.jpg)

Additional folder created:

![newfoldercreatesandbox](https://cloud.githubusercontent.com/assets/6186615/6352791/3441848c-bc13-11e4-8338-14692ce19d4f.jpg)

Invoked new sandbox wizard on new folder:

![newfoldersandboxwizard](https://cloud.githubusercontent.com/assets/6186615/6352804/455b5ae0-bc13-11e4-8fdc-c6f3d5d55de3.jpg)

Two sandboxes created:

![finish](https://cloud.githubusercontent.com/assets/6186615/6352815/4f61c54c-bc13-11e4-839d-08b1879fb399.jpg)

**Comment by gisraeli** [comment]
@atusek  which build did you verify with?

**Comment by atusek** [comment]
Above steps verified with build 1.0.51.0

**Comment by KristinaTaylor** [comment]
Reviewed & Verified.
