### ISSUE TITLE
Configure AppVeyor to produce languages installer artifacts

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#58]
This is a "build" activity. It involves adding the languages project to the visual studio solution, as well as making sure that AppVeyor is hooked up correctly to produce the installer artifacts. We should be producing MSIs, not MSMs.

The only verification would be to check that the artifacts are being produced.

**Comment by KristinaTaylor** [comment]
The languages that Integrity currently supports include 2 Chinese variants, Japanese, and German. These installers should be kept around, since the English language will be the default.

**Comment by bleskows** [comment]
I guess I can pick this one up, since I know most about how the AppVeyor CI build system works. Please assign to me.

**Comment by bleskows** [comment]
Changing title since code changes will occur in issue #59. Work in this issue will be to configure AppVeyor appropriately.

**Comment by sharonzhao** [comment]
Verified with build 1.0.84.0:
The following artifacts have been produced for both Win 32 and 64 bits
- TortoiseSI-LanguagePack-ja.msi
- TortoiseSI-LanguagePack-zh_TW.msi
- TortoiseSI-LanguagePack-zh_CN.msi
- TortoiseSI-LanguagePack-de.msi

**Comment by KristinaTaylor** [comment]
Reviewed during sprint review.
