### ISSUE TITLE
Configure VS project to build language pack installers. Make multiple languages testable

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#59]
Make it possible for TortoiseSI to pick up the language from the host executable process for our DLL, and attempt to use the right resource DLL to pick up the appropriate language. Add a sample language, and figure out how to switch the locale easily for testing purposes. Test with missing translations (resource strings). Should fall back to English for any missing translations.

**Comment by KristinaTaylor** [comment]
@gisraeli says: see loadLangDLL

**Comment by gisraeli** [comment]
LoadLangDll is in ShellExt.cpp

**Comment by bleskows** [comment]
Changing title since the VS studio build work is being done with the necessary code changes.

**Comment by atusek** [comment]
@KristinaTaylor  Banners for the language pack installers are different from the application. I have used the general application banners for now, but they don't show up correctly in the installer. Can we get updated images?

![image](https://cloud.githubusercontent.com/assets/6186615/6528154/19480d26-c3ee-11e4-8e7a-ce4158d258a6.png)

Also, the TortoiseGIT image contains text indicating "Language Pack"

![dialog](https://cloud.githubusercontent.com/assets/6186615/6528216/78043c86-c3ee-11e4-96ff-92c21f5ec18b.jpg)

**Comment by atusek** [comment]
@KristinaTaylor First screen of installer looks like this 

![image](https://cloud.githubusercontent.com/assets/6186615/6528292/fcc472ec-c3ee-11e4-9c92-0cb96d16a580.png)

**Comment by KristinaTaylor** [comment]
Could we edit the header in the banner of the installer for the language packs to at least have the text right aligned? Not sure if the text will fit in all languages, but we would have to get input from a speaker of each language in order to update it.

I'm ok with leaving the other one as a generic "TortoiseSI" image to close off this issue, but I'll see about getting an update with a subtitle of some sort. Moved to #86.

**Comment by bleskows** [comment]
@atusek Just remembered, don't forget to add the appropriate info for the registry key for debugging languages to the wiki.

**Comment by atusek** [comment]
Info regarding registry key has been added to the wiki.

**Comment by KristinaTaylor** [comment]
Reviewed during sprint review - actual localization will be formally tested when we have translations.

**Comment by bleskows** [comment]
Removed needs docs: documented in Alpha release User Guide
