### ISSUE TITLE
Gather a list of needed icons

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#7]
We need a list of necessary icons, so that we can submit a request for them to be created.

For their context menu groups, TortoiseGit and TortoiseSVN both use a turtle, with a folder overlay. Because we'll be interacting with PTC Integrity, which uses sandboxes, we should use a tortoise with a PTC Integrity sandbox icon.

What other icons will we need, that can't be reused from the Tortoise ones?  
What size do each of the images or icons need to be?
What images does the installer have/need?

**Comment by gisraeli** [comment]
Off of the top of my head these are the actions we will have:
- ```
     Add (file / folder)
  ```
- ```
     Drop (file / folder)
  ```
- ```
     Move (file / folder)
  ```
- ```
     Rename (file / folder)
  ```
- ```
     Lock file
  ```
- ```
     Unlock file
  ```
- ```
     Revert file (folder?)
  ```
- ```
     Resync entire sandbox
  ```
- ```
     Resync file by CP
  ```
- ```
     Create sandbox
  ```
- ```
     Drop (top level) sandbox
  ```
- ```
     Retarget sandbox
  ```
- ```
     Launch sandbox view
  ```
- ```
     Launch member history view
  ```
- ```
     Launch local changes diff view
  ```
- ```
     Launch incoming changes diff view
  ```
- ```
     Launch annotated revision view
  ```
- ```
     Launch my change packages view
  ```
- ```
     Launch my change package reviews view
  ```
- ```
     Launch Integrity gui
  ```

We’d want to look at the repository and see if there are appropriate icons for these (and not all of them need icons)

**Comment by KristinaTaylor** [comment]
As we add file & folder operations, we will be assessing which icons from TortoiseGit/SVN can be applied to Integrity operations.
