### ISSUE TITLE
Update icon in right-click context menu with src/TortoiseSISetup/include/tsvnmenufolder.ico

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#72]
Should probably also rename to tsimenufolder.ico.

**Comment by KristinaTaylor** [comment]
Can we do anything on these ones, too?

![image](https://cloud.githubusercontent.com/assets/10520385/6506692/d3d96a38-c31a-11e4-9dd8-2cd65d4f4d94.png)

(I just double checked, and the icons in the screenshot above are the same in build 68).

**Comment by bleskows** [comment]
Move tortoise.ico from src/TortoiseSISetup/include into src/Resources. We may also need a smaller version of this icon since the other menu icons are 12x12 or 16x16

**Comment by KristinaTaylor** [comment]
tsvnmenufolder.ico is 16x16. I think we'd want to use this one for the menu, and tortoise.ico for the programs & features. If you need me to request a different size for tortoise.ico, let me know.

**Comment by sharonzhao** [comment]
Verified with build 1.0.85.0:
- The TortoiseSI icon in the right-click context menu has been updated.
- The TortoiseSI icon has been updated in the programs & features.
