### ISSUE TITLE
Create initial submit CP dialog

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#75]
Should start with: 
-drop down of open change packages
-submit CP button
-cancel button

In the drop down, the default selected CP should be the active CP from the Integrity Client.

**Comment by flemingg** [comment]
:ballot_box_with_check: Re-establish dependent libraries (Resizeable, Lexer, Graph, Spell and Async).
:ballot_box_with_check: Create dialog layout for “SI Commit” (resource).
:black_large_square: Re-establish TortoiseSIProc command framework (main app):
  &nbsp;&nbsp; :ballot_box_with_check: Write code for “SI Commit” command (creates SI Commit window).
&nbsp;&nbsp; :black_large_square: Pair-down TortoiseSIProc commands
:black_large_square: Write code for “SI Commit” controls
 &nbsp;&nbsp; :black_large_square: Server connection handling
&nbsp;&nbsp; :black_large_square: Integrity actions
&nbsp;&nbsp; :black_large_square: Integrity response
&nbsp;&nbsp; :black_large_square: Callbacks:
&nbsp;&nbsp;&nbsp;&nbsp; :ballot_box_with_check: Initialization
&nbsp;&nbsp;&nbsp;&nbsp; :black_large_square: Create CP
&nbsp;&nbsp;&nbsp;&nbsp; :black_large_square: Submit CP
&nbsp;&nbsp;&nbsp;&nbsp; :black_large_square: Cancel
&nbsp;&nbsp;&nbsp;&nbsp; :black_large_square: Write code for context menu "Create CP"

**Comment by KristinaTaylor** [comment]
Posted #94, #95, and #96 to split out some of the remaining work.

**Comment by KristinaTaylor** [comment]
From alpha-release readiness review session: it looks like this needs to be added to the build & the installer.

**Comment by KristinaTaylor** [comment]
Closing this issue, as far as the Alpha release is concerned. The initial dialog is in build 155 and later. 

Other issues cover completing the work for this dialog, and all bugs that have been found so far have been posted separately.
