### ISSUE TITLE
Create sandbox gesture should not launch the sandbox view

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#85]
This is controlled by the [no]openView option (aka View sandbox After Creation).

**Comment by bleskows** [comment]
Can be verified with build [1.0.101.0](https://ci.appveyor.com/project/PTC-ALM/tortoisesi/build/1.0.101.0) or later

**Comment by KristinaTaylor** [comment]
Reviewed during sprint review.
