### ISSUE TITLE
Update languages installer to fix overlapping text in banner

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#86]
Split from issue #59. 

![screenshot](https://cloud.githubusercontent.com/assets/6186615/6528154/19480d26-c3ee-11e4-8e7a-ce4158d258a6.png)

Fixing this issue will likely involve adding a custom wix ui, similar to the main installer project.

**Comment by atusek** [comment]
@KristinaTaylor Right justifying the text still causes overlap with the banner icon:

![languageinstaller](https://cloud.githubusercontent.com/assets/6186615/6667009/8bb34ed8-cbbf-11e4-9d54-a2f3935d763c.jpg)

I suggest we remove the banner text altogether. I think there is enough information in the dialog for the  user to understand what it being installed. See below:

![languageinstaller_notitle](https://cloud.githubusercontent.com/assets/6186615/6667147/81347828-cbc0-11e4-98a8-15403fa41cf2.jpg)

Thoughts?

**Comment by KristinaTaylor** [comment]
Agreed. I think this will look much cleaner.

**Comment by atusek** [comment]
OK...I will make the change.

**Comment by KristinaTaylor** [comment]
Reviewed during sprint review.
