### ISSUE TITLE
Sandbox folder operations

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#9]
We need to add support for drop, retarget, and resynchronize on sandboxes.

We need to find a way to clarify to the user what selection the operation will apply to.  If the user chooses to resynchronize on a folder that is inside a subproject, will they expect it to apply to the files in that folder, the files in the current folder, the files in that subproject, or the files in the top-level sandbox? If we only provide access to resynchronize on the top level sandbox, that's not very discoverable for the users.

We could provide a shortcut for "open the top level sandbox," but users may not know why they'd want to do that, and may not notice commands that are ONLY available at that level.

**Comment by KristinaTaylor** [comment]
Note that Resynchronize Entire Sandbox, Drop Sandbox, and Retarget Sandbox should be available regardless of where in the sandbox directory hierarchy the user is, and for single selection only.

## Resynchronize by Change Package

This will allow multi-select, but only on controlled files or folders.
**File Selection:** can only resynchronize by cp
**Folder selection:** Resynchronize all files in this folder and all subfolders by CP
**User is in a folder:** Resynchronize files in this folder by CP

## Resynchronize Entire Sandbox

Resynchronizes the sandbox, from the top level sandbox. Follow the client preferences for overwrite & prompting.

## Drop Sandbox

Drops the Sandbox from the top level. This follows client preferences for deleting contents, which may ultimately fail (if a directory in the sandbox is open)

## Retarget Sandbox

Retargets the sandbox (change variant or build revision) at the top level. This follows client preferences & dialogs.

**Comment by atusek** [comment]
The resync operation will only allow multi select on files. Resync operation will not be available if multi select includes a folder.

**Comment by gisraeli** [comment]
I'll verify this one

**Comment by gisraeli** [comment]
while trying to drop, resync and entire a sandbox, or retarget it:

![image](https://cloud.githubusercontent.com/assets/10521380/6353928/36730080-bc1a-11e4-8c28-9f16b05666c9.png)

**Comment by gisraeli** [comment]
with this setup:

![image](https://cloud.githubusercontent.com/assets/10521380/6353968/7765a836-bc1a-11e4-880a-dc2d463bb399.png)

**Comment by KristinaTaylor** [comment]
From Review session: Could we add the words "by Change Package" to the Resynchronize menu action.

**Comment by sharonzhao** [comment]
Tested with build 1.0.64.0:
- Resynchronize by Change Package allows both single and multiple selection on files.It resynchronizes files by CP
- Resynchronize Entire Sandbox resynchronizes the sandbox from the top level
- Drop Sandbox drops the sandbox from the top level
- Retarget Sandbox retargets the sandbox at the top level
- Resynchronize Entire Sandbox, Drop Sandbox, and Retarget Sandbox is available regardless of where in the sandbox directory hierarchy the user is, and for single selection only

**Comment by KristinaTaylor** [comment]
Demonstrated in Review.

**Comment by bleskows** [comment]
Removed needs docs: documented in Alpha release User Guide
