### ISSUE TITLE
Callbacks for submit CP dialog

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#94]
Callbacks:
     :ballot_box_with_check: Initialization
     :ballot_box_with_check: Create CP
     :ballot_box_with_check: Submit CP
     :ballot_box_with_check:  Cancel
     :black_large_square: Write code for context menu "Create CP"

**Comment by flemingg** [comment]
Callbacks for initializing commit dialog, create cp, submit cp and cancel have been added to TortoiseSIProc SICommitDialog.

**Comment by KristinaTaylor** [comment]
Closed off during sprint review - won't be tested independently.
