### ISSUE TITLE
Server connection handling for Submit CP dialogs

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#95]

**Comment by flemingg** [comment]
Server connection handling has been added to TortoiseSIProcApp.

**Comment by KristinaTaylor** [comment]
@flemingg is going to make an additional change here to trap exceptions if we're not connected when we think we are. 

An additional issue will be posted to make connection handling more robust (listening to events from the client).

**Comment by KristinaTaylor** [comment]
Closing this issue - this will be tested when the submit changes dialog is complete. The server connection handling has been handled, here.
