### ISSUE TITLE
Add menu option to launch Working File Changes view

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#97]
Should be available on a sandbox selection.

**Comment by bleskowskyPTC** [comment]
Can be verified with build [1.0.110.0](https://ci.appveyor.com/project/PTC-ALM/tortoisesi/build/1.0.110.0) or later

**Comment by bleskows** [comment]
Wrong issue :)

**Comment by bleskows** [comment]
Sample command:
si si.WorkingFileChangesView --sandbox=<"sandbox"> -g. Minor note, only the GUI view is published; the command itself is mostly intended for internal use.

**Comment by KristinaTaylor** [comment]
This is now available - reviewed during sprint review. No test cases will be added, as this is a temporary solution as a way to allow users to submit changes in the 'alpha' version of this integration.
