### ISSUE TITLE
Rename should be available on single select only

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#98]

**Comment by bleskows** [comment]
Can be verified with build [1.0.110.0](https://ci.appveyor.com/project/PTC-ALM/tortoisesi/build/1.0.110.0) or later

**Comment by sharonzhao** [comment]
Verified using build 1.0.112.0: Rename is available on single select only.

This issue can be closed.

**Comment by KristinaTaylor** [comment]
Reviewed in Sprint 9 review. Closing.
